# 1. ПЕРЕМИКАЄМО РОЛЬ НА CENTRAL (Це виправить помилки undefined symbol)
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# 2. ПІДТРИМКА BLE ТА USB (Необхідно для віджетів)
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y

# 3. ТРЕКБОЛ ТА СТУДІЯ
CONFIG_SPI=y
CONFIG_PMW3610_ALT=y
CONFIG_ZMK_STUDIO=y

# 4. ГРАФІЧНА БАТАРЕЙКА (Тільки картинка)
CONFIG_NICE_OLED_WIDGET_BATTERY=y
CONFIG_NICE_OLED_WIDGET_BATTERY_IMAGE=y
CONFIG_NICE_OLED_WIDGET_BATTERY_PERCENTAGE=n
CONFIG_NICE_OLED_WIDGET_BATTERY_LABEL=n

# 5. ГРАФІЧНИЙ СТАТУС ВИВОДУ (Тільки картинка)
CONFIG_NICE_OLED_WIDGET_OUTPUT=y
CONFIG_NICE_OLED_WIDGET_OUTPUT_IMAGE=y
CONFIG_NICE_OLED_WIDGET_OUTPUT_TEXT=n
CONFIG_NICE_OLED_WIDGET_OUTPUT_LABEL=n
CONFIG_NICE_OLED_WIDGET_OUTPUT_BACKGROUND=n

# 6. WPM ТА LUNA
CONFIG_ZMK_WPM=y
CONFIG_NICE_OLED_WIDGET_WPM=y
CONFIG_NICE_OLED_WIDGET_WPM_NUMBER=n
CONFIG_NICE_OLED_WIDGET_WPM_GRAPH=y
CONFIG_NICE_OLED_WIDGET_WPM_LUNA=y

# 7. КООРДИНАТИ
CONFIG_NICE_OLED_WIDGET_BATTERY_CUSTOM_X=0
CONFIG_NICE_OLED_WIDGET_BATTERY_CUSTOM_Y=0
CONFIG_NICE_OLED_WIDGET_OUTPUT_USB_CUSTOM_X=45
CONFIG_NICE_OLED_WIDGET_OUTPUT_BT_CUSTOM_X=49
