CONFIG_SPI=y
CONFIG_PMW3610_ALT=y

## Central-only split features (переніс сюди щоб не ламало ліву половинку)
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

## Luna (WPM widget)
CONFIG_ZMK_WPM=y
CONFIG_NICE_OLED_WIDGET_WPM=y
CONFIG_NICE_OLED_WIDGET_WPM_NUMBER=y
CONFIG_NICE_OLED_WIDGET_WPM_LUNA=y
CONFIG_NICE_OLED_WIDGET_WPM_LUNA_ANIMATION_MS=300
