## SPI для дисплея
CONFIG_SPI=y

## Анімація Spaceman
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SPACEMAN=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_MS=960

# Вимикаємо зайве
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_GEM=n

## Смарт-батарейка для периферії
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SMART_BATTERY=y
