## Peripheral animation (Spaceman)
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SPACEMAN=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_MS=960

## Do NOT enable central-only split battery flags here
## Do NOT enable trackball driver here (unless the sensor is physically on the left)
