## Bluetooth
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

CONFIG_BT_PERIPHERAL_PREF_MAX_INT=9
CONFIG_BT_PERIPHERAL_PREF_LATENCY=16
CONFIG_BT_BUF_ACL_TX_COUNT=32
CONFIG_BT_L2CAP_TX_BUF_COUNT=32

## Power
CONFIG_ZMK_SLEEP=y
CONFIG_PM_DEVICE=y
CONFIG_ZMK_EXT_POWER=y

## Battery reporting (safe globally)
CONFIG_ZMK_BATTERY_REPORTING=y

## Pointing / input
CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y

## Queue
CONFIG_ZMK_BEHAVIORS_QUEUE_SIZE=512

## Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Battery icon (top-left)
CONFIG_NICE_OLED_WIDGET_BATTERY=y
CONFIG_NICE_OLED_WIDGET_BATTERY_CUSTOM_X=0
CONFIG_NICE_OLED_WIDGET_BATTERY_CUSTOM_Y=0

# Output icons (top-right)
CONFIG_NICE_OLED_WIDGET_OUTPUT=y
CONFIG_NICE_OLED_WIDGET_OUTPUT_USB_CUSTOM_X=145
CONFIG_NICE_OLED_WIDGET_OUTPUT_USB_CUSTOM_Y=0
CONFIG_NICE_OLED_WIDGET_OUTPUT_BT_CUSTOM_X=145
CONFIG_NICE_OLED_WIDGET_OUTPUT_BT_CUSTOM_Y=0
CONFIG_NICE_OLED_WIDGET_OUTPUT_BT_UNBONDED_CUSTOM_X=140
CONFIG_NICE_OLED_WIDGET_OUTPUT_BT_UNBONDED_CUSTOM_Y=0

## Display perf (для анімацій)
CONFIG_LV_Z_MEM_POOL_SIZE=8192
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=3072
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
