manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: semtexfromua
      url-base: https://github.com/semtexfromua
    - name: kevinpastor
      url-base: https://github.com/kevinpastor
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
    - name: zmk-split-peripheral-input-relay
      remote: badjeff
      revision: main
    - name: zmk-input-behavior-listener-custom
      remote: semtexfromua
      revision: f915f593bd63c9e8b45cb763b6c87ccd6a2aa465  # scroll-axis-lock @ 2026-06-12 (axis-locked scroll + dead-zone fix + lockout-ms)
    - name: nice-view-elemental
      remote: kevinpastor
      revision: 69c2ecd56b0b870ddb94b79110ef5a2152ca4a3a
  self:
    path: config
